<?php
$tasks = array(
    ['',90],
    ['-s "test.png" -g #g#',0],
    ['-s test.png -g #g#',0],
    ['-s test.jpg -g #g#',0],
    ['-s test.bmp -g #g#',0],
    ['-s test.txt -g #g#',71],
    ['-s test.png -g error',255],
    ['-s test.png -g',255],
    ['-s',255],
    ['-s *',255],
    ['-s /',255],
    ['-s test.jpg -o #g#_test_#i#.jpg -g #g#',0],
    ['-s test.jpg -o #g#_test_#i#.png -g #g#',0],
    ['-s test.jpg -o #g#_test_#i#.bmp -g #g#',71],
    ['-s test.jpg -o',255],
    ['-s test.jpg -o *',255],
    ['-s test.jpg -o /',255],
    ['-s test.png -o #g#_test_#i#.png -c -g #g#',0],
    ['-s test.png -o #g#_test_#i#.png -c=1024 -g #g#',0],
    ['-s test.png -o #g#_test_#i#.png -c=512 -g #g#',0],
    ['-s test.png -o #g#_test_#i#.png -c=-512 -g #g#',255],
    ['-s test.png -o #g#_test_#i#.png -c="512" -g #g#',255],
    ['-s test.png -o #g#_test_#i#.png -c=error -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -c -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -c -g #g#',0],
    ['-s test.png -g #g# -v=0',0],
    ['-s test.png -g #g# -v',0],
    ['-s test.png --v=error',255],
    ['-s test.png -v=5',255],
    ['-s test.png -v=-5',255],
    ['-s test.png -v=5-',255],
    ['-s test.png -v=-',255],
    ['-s test.png -v=*',255],
    ['-s test.png --help',0],
    ['-s test.png --help -v',0],
    ['-s test.png --help error',255],
    ['-s test.png -d -g #g#',0],
    ['-s test.png -d 123 -g #g#',255],
    ['-s test.png -d error -g #g#',255],
    ['-s test1.png -d -g #g#',0],
    ['-s test2.png -d -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t 20 -r 20 -b 20 -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -l 40 -t 20 -b 20 -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -l -t 20 -r 20 -b 20 -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t -r 20 -b 20 -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t 20 -r -b 20 -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t 20 -r 20 -b -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l error -t 20 -r 20 -b 20 -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t error -r 20 -b 20 -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t 20 -r error -b 20 -g #g#',255],
    ['-s test1.png -o #g#_test_#i#.png -l 0 -t 20 -r 20 -b error -g #g#',255],
);
?>