<?php
$tasks = array(
['',90],
    ['-s "test.png" -g #g#',0],
    ['-s test.png -g #g#',0],
    ['-s test.jpg -g #g#',0],
    ['-s test.bmp -g #g#',0],
    ['-s test.txt -g #g#',71],
    ['-s test.png -g error',255],
    ['-s test.png -g',255],
    ['-s',255],
    ['-s *',255],
    ['-s /',255],
    ['-s test.png -o #g#_test_#i# -g #g#',0],
    ['-s test.png -o ../#g#_test_#i# -g #g#',0],
    ['-s test.png -o #g#_test_#i#.png -g #g#',71],
    ['-s test.png -o',255],
    ['-s test.png -o *',255],
    ['-s test.png -o /',255],
    ['-s test.png -g #g# -v=0',0],
    ['-s test.png -g #g# -v',0],
    ['-s test.png -v=error',255],
    ['-s test.png -v=5',255],
    ['-s test.png -v=-5',255],
    ['-s test.png -v=5-',255],
    ['-s test.png -v=-',255],
    ['-s test.png -v=*',255],
    ['-s test.png --help',0],
    ['-s test.png --help error',255],
    ['-s test.png -t map',0],
    ['-s test.png -t 255',255],
    ['-s test.png -t',255],
    ['-s test.png -t *',255],
    ['-s test.png -t /',255],
);
?>
