<?php
$tasks = array(
['',90],
    ['-s "test.png" -g #g#',0],
    ['-s test.png -g #g#',0],
    ['-s test.jpg -g #g#',0],
    ['-s test.bmp -g #g#',0],
    ['-s test.txt -g #g#',71],
    ['-s test.png -g error',255],
    ['-s test.png -g',255],
    ['-s',255],
    ['-s *',255],
    ['-s /',255],
    ['-s test.jpg -o #g#_test_#i#.jpg -g #g#',0],
    ['-s test.jpg -o #g#_test_#i#.png -g #g#',0],
    ['-s test.jpg -o #g#_test_#i#.bmp -g #g#',71],
    ['-s test.jpg -o',255],
    ['-s test.jpg -o *',255],
    ['-s test.jpg -o /',255],
    ['-s test1.png -o #g#_test_#i#.png -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -g #g#',0],
    ['-s test.png -g #g# -v=0',0],
    ['-s test.png -g #g# -v',0],
    ['-s test.png --v=error',255],
    ['-s test.png -v=5',255],
    ['-s test.png -v=-5',255],
    ['-s test.png -v=5-',255],
    ['-s test.png -v=-',255],
    ['-s test.png -v=*',255],
    ['-s test.png --help',0],
    ['-s test.png --help -v',0],
    ['-s test.png --help error',255],
    ['-s test.jpg -l 4',0],
    ['-s test.jpg -l -2',255],
    ['-s test.jpg -l 255',255],
    ['-s test.jpg -l "test"',255],
    ['-s test.jpg -l test',255],
    ['-s test.jpg -l',255],
    ['-s test.jpg -l *',255],
    ['-s test.jpg -l /',255],
);
?>