<?php
$tasks = array(
    ['',90],
    ['-s "test.png" -g #g#',0],
    ['-s test.png -g #g#',0],
    ['-s test.jpg -g #g#',0],
    ['-s test.bmp -g #g#',0],
    ['-s test.txt -g #g#',71],
    ['-s test.png -g error',255],
    ['-s test.png -g',255],
    ['-s',255],
    ['-s *',255],
    ['-s /',255],
    ['-s test.jpg -o #g#_test_#i#.jpg -g #g#',0],
    ['-s test.jpg -o #g#_test_#i#.png -g #g#',0],
    ['-s test.jpg -o #g#_test_#i#.bmp -g #g#',71],
    ['-s test.jpg -o',255],
    ['-s test.jpg -o *',255],
    ['-s test.jpg -o /',255],
    ['-s test1.png -o #g#_test_#i#.png -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -g #g#',0],
    ['-s test.png -g #g# -v=0',0],
    ['-s test.png -g #g# -v',0],
    ['-s test.png --v=error',255],
    ['-s test.png -v=5',255],
    ['-s test.png -v=-5',255],
    ['-s test.png -v=5-',255],
    ['-s test.png -v=-',255],
    ['-s test.png -v=*',255],
    ['-s test.png --help',0],
    ['-s test.png --help -v',0],
    ['-s test.png --help error',255],
    ['-s test1.png -o #g#_test_#i#.png -w 4096 -h 2048 -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -w 4096 -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -h 2048 -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -w 1024 -h 512 -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -w 1024 -g #g#',0],
    ['-s test1.png -o #g#_test_#i#.png -h 512 -g #g#',0],
    ['-s test2.png -o #g#_test_#i#.png -w -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -w "1024" -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -w error -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -w - -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -w * -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -h -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -h "1024" -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -h error -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -h - -g #g#',255],
    ['-s test2.png -o #g#_test_#i#.png -h * -g #g#',255],
);
?>